spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/ms-producto
    username: root
    hikari:
      password:
    driver-class-name: com.mysql.cj.jdbc.Driver
# SWAGGER OPEN API
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

